### ISSUE TITLE
WordPress 5.8 Widget/Sidebar area

### ISSUE THREAD

**Issue by grappler** [wearerequired/WP-Widget-Disable#52]
In WordPress 5.8 the sidebar area has moved to a block area. The [old core widgets](https://developer.wordpress.org/reference/hooks/widget_types_to_hide_from_legacy_widget_block/) cannot be added.

Do we hide the Widget settings if the classic area is not enabled?

Do we create a new setting to disable the blocks for the widget area?

**Comment by ocean90** [comment]
> The old widgets cannot be added.

That doesn't seem to be true, at least for third-party widgets which still can be added through the Legacy Widget block. Lucky for us, if a widget is disabled it's not listed as an option in this block.

There's at least one thing we can do: Hide (or disable the checkbox of) all widgets which are listed in `get_legacy_widget_block_editor_settings()['widgetTypesToHideFromLegacyWidgetBlock']` if the Classic Widgets plugin is not active.
By default that would affect these core widgets:

* `pages`
* `calendar`
* `archives`
* `media_audio`
* `media_image`
* `media_gallery`
* `media_video`
* `search`
* `text`
* `categories`
* `recent-posts`
* `recent-comments`
* `rss`
* `tag_cloud`
* `custom_html`
* `block`

Due to the complexity of removing blocks (not all blocks are registered server-side) I'd leave that out for later. Note that it's already possible to "disable" blocks on a per-user basis through the editor settings panel.
